#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY=""
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	# If using Drupal 7, uncomment this line:
	# copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/default.local-settings.php" "${SITEDIR_PATH}/local-settings.php"
	# If using Drupal 8, uncomment this line:
	copy_settings_file "${PROJECT_ROOT}/.docksal/wordpress/wp-config-local.php" "${SITEDIR_PATH}/wp-config-local.php"

	# Copy htaccess
	copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/default.htaccess" "${DOCROOT_PATH}/.htaccess"

	# Append this to the wp-config.php: 
	# ```
	# /**
	#  * Include wp-config-local.php if it exists.
	#  */
	# if ( file_exists( dirname( __FILE__ ) . '/wp-config-local.php' ) ) {
	# 	include( dirname( __FILE__ ) . '/wp-config-local.php' );
	# }
	# ```
	
	# Begin
	echo "Appending wp-config-local.php to wp-config.php..."
	echo "/**" >> "${SITEDIR_PATH}/wp-config.php"
	echo " * Include wp-config-local.php if it exists." >> "${SITEDIR_PATH}/wp-config.php"
	echo " */" >> "${SITEDIR_PATH}/wp-config.php"
	echo "if ( file_exists( dirname( __FILE__ ) . '/wp-config-local.php' ) ) {" >> "${SITEDIR_PATH}/wp-config.php"
	echo "	include( dirname( __FILE__ ) . '/wp-config-local.php' );" >> "${SITEDIR_PATH}/wp-config.php"
	echo "}" >> "${SITEDIR_PATH}/wp-config.php"
	# End
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	# chmod 755 "${SITEDIR_PATH}"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
init_settings

#-------------------------- END: Execution --------------------------------
