#!/usr/bin/env bash

# Rsync the files from the Pantheon instance to the local site.
# Note this is dependent on the terminus rsync plugin:
# https://github.com/pantheon-systems/terminus-rsync-plugin

echo "Rsyncing files from ${PROJECT_NAME}.${PANTHEON_SITE_ENV}"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
dest="${DOCROOT_PATH}/wp-content/uploads"
terminus rsync ${PROJECT_NAME}.${PANTHEON_SITE_ENV}:files/ ${dest}
